apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxrchung-rails
  labels:
    app: maxrchung-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxrchung-rails
  template:
    metadata:
      labels:
        app: maxrchung-rails
    spec:
      containers:
      - name: maxrchung
        image: maxrchung/maxrchung-rails
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          value: {{ .Values.secretKeyBase }}
        - name: RAILS_ENV
          value: {{ .Values.railsEnv }}
{{- if .Values.local }}
        volumeMounts:
        - mountPath: /app
          name: maxrchung-rails
      volumes:
        - name: maxrchung-rails
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory
{{- end }}