{{- if .Values.local }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maxrchung-rails
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maxrchung-rails
            port:
              number: 80
{{- end }}